### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by shuntagami** [shuntagami/dotfiles#29]
[sample.txt](https://github.com/shuntagami/dotfiles/files/12756041/sample.txt)

**Comment by shuntagami** [comment]
```
~/dotfiles main*
❯ update
Brewfile                    default-gems                tslint.json
com.googlecode.iterm2.plist default-packages
Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license accept
Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license accept
Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license accept
Error: You have not agreed to the Xcode license. Please resolve this by running:
  sudo xcodebuild -license accept

changed 18 packages in 1s

28 packages are looking for funding
  run `npm fund` for details

changed 18 packages in 892ms

28 packages are looking for funding
  run `npm fund` for details
Updating rubygems-update
Fetching rubygems-update-3.4.20.gem
Successfully installed rubygems-update-3.4.20
Parsing documentation for rubygems-update-3.4.20
Installing ri documentation for rubygems-update-3.4.20
Installing darkfish documentation for rubygems-update-3.4.20
Done installing documentation for rubygems-update after 0 seconds
Parsing documentation for rubygems-update-3.4.20
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 3.4.20
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted @ rb_sysopen - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/gem
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1387:in `initialize'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1387:in `open'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1387:in `block in copy_file'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1386:in `open'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1386:in `copy_file'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:492:in `copy_file'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:860:in `block in install'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1558:in `block in fu_each_src_dest'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1574:in `fu_each_src_dest0'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1556:in `fu_each_src_dest'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:856:in `install'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.20/lib/rubygems/commands/setup_command.rb:268:in `block (2 levels) in install_executables'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.20/lib/rubygems/commands/setup_command.rb:252:in `chdir'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.20/lib/rubygems/commands/setup_command.rb:252:in `block in install_executables'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.20/lib/rubygems/commands/setup_command.rb:249:in `each'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.20/lib/rubygems/commands/setup_command.rb:249:in `install_executables'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.20/lib/rubygems/commands/setup_command.rb:166:in `execute'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.20/lib/rubygems/command.rb:328:in `invoke_with_build_args'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.20/lib/rubygems/command_manager.rb:253:in `invoke_command'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.20/lib/rubygems/command_manager.rb:193:in `process_args'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.20/lib/rubygems/command_manager.rb:151:in `run'
	/Library/Ruby/Gems/2.6.0/gems/rubygems-update-3.4.20/lib/rubygems/gem_runner.rb:52:in `run'
	setup.rb:34:in `<main>'
Updating installed gems
Updating CFPropertyList
Fetching CFPropertyList-3.0.6.gem
Fetching rexml-3.2.6.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:713:in `verify_gem_home'
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:903:in `pre_install_checks'
	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:303:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/resolver/specification.rb:105:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:195:in `block in install'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:183:in `each'
	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:183:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/dependency_installer.rb:251:in `install'
	/Library/Ruby/Site/2.6.0/rubygems/commands/update_command.rb:247:in `update_gem'
	/Library/Ruby/Site/2.6.0/rubygems/commands/update_command.rb:259:in `block in update_gems'
	/Library/Ruby/Site/2.6.0/rubygems/commands/update_command.rb:258:in `each'
	/Library/Ruby/Site/2.6.0/rubygems/commands/update_command.rb:258:in `update_gems'
	/Library/Ruby/Site/2.6.0/rubygems/commands/update_command.rb:120:in `execute'
	/Library/Ruby/Site/2.6.0/rubygems/command.rb:328:in `invoke_with_build_args'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:253:in `invoke_command'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:193:in `process_args'
	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:151:in `run'
	/Library/Ruby/Site/2.6.0/rubygems/gem_runner.rb:52:in `run'
	/usr/bin/gem:21:in `<main>'
Cleaning up installed gems...
Clean up complete
```

**Comment by shuntagami** [comment]
```
~/dotfiles main*
❯ sudo xcodebuild -license accept

~/dotfiles main*
❯ update
com.googlecode.iterm2.plist default-gems                default-packages            tslint.json
==> Homebrew collects anonymous analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics have been recorded yet (nor will be during this `brew` run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

Installing from the API is now the default behaviour!
You can save space and time by running:
  brew untap homebrew/core
  brew untap homebrew/cask
Already up-to-date.
Error: No Brewfile found
Removing: /Users/shun.tagami/Library/Caches/Homebrew/python-pytz--2023.3.post1... (822.9KB)
Removing: /Users/shun.tagami/Library/Caches/Homebrew/go_cache... (24,039 files, 700.3MB)
Removing: /Users/shun.tagami/Library/Caches/Homebrew/api-source/Homebrew/homebrew-cask/730d3404db7e5a8b309e9d8ad64ff8abef52f597/Cask/docker.rb... (5.2KB)
Pruned 0 symbolic links and 23 directories from /opt/homebrew
==> This operation has freed approximately 701MB of disk space.
```

**Comment by shuntagami** [comment]
`sudo softwareupdate --install-rosetta`

**Comment by shuntagami** [comment]
```
~/dotfiles main*
❯ ~/dotfiles/scripts/deploy.sh
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:5> [ ! -d /Users/shun.tagami/.zprezto ']'
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:10> setopt EXTENDED_GLOB
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:11> rcfile=/Users/shun.tagami/.zprezto/runcoms/zlogin
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:12> ln -sf /Users/shun.tagami/.zprezto/runcoms/zlogin /Users/shun.tagami/.zlogin
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:11> rcfile=/Users/shun.tagami/.zprezto/runcoms/zlogout
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:12> ln -sf /Users/shun.tagami/.zprezto/runcoms/zlogout /Users/shun.tagami/.zlogout
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:11> rcfile=/Users/shun.tagami/.zprezto/runcoms/zpreztorc
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:12> ln -sf /Users/shun.tagami/.zprezto/runcoms/zpreztorc /Users/shun.tagami/.zpreztorc
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:11> rcfile=/Users/shun.tagami/.zprezto/runcoms/zprofile
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:12> ln -sf /Users/shun.tagami/.zprezto/runcoms/zprofile /Users/shun.tagami/.zprofile
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:11> rcfile=/Users/shun.tagami/.zprezto/runcoms/zshenv
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:12> ln -sf /Users/shun.tagami/.zprezto/runcoms/zshenv /Users/shun.tagami/.zshenv
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:11> rcfile=/Users/shun.tagami/.zprezto/runcoms/zshrc
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:12> ln -sf /Users/shun.tagami/.zprezto/runcoms/zshrc /Users/shun.tagami/.zshrc
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:16> cd /Users/shun.tagami/.zprezto
+_direnv_hook:1> trap -- '' SIGINT
+_direnv_hook:2> /opt/homebrew/bin/direnv export zsh
+_direnv_hook:2> eval ''
+_direnv_hook:3> trap - SIGINT
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:16> git pull
Already up to date.
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:16> git submodule sync --recursive
Synchronizing submodule url for 'modules/autosuggestions/external'
Synchronizing submodule url for 'modules/completion/external'
Synchronizing submodule url for 'modules/fasd/external'
Synchronizing submodule url for 'modules/history-substring-search/external'
Synchronizing submodule url for 'modules/prompt/external/agnoster'
Synchronizing submodule url for 'modules/prompt/external/async'
Synchronizing submodule url for 'modules/prompt/external/powerlevel10k'
Synchronizing submodule url for 'modules/prompt/external/powerline'
Synchronizing submodule url for 'modules/prompt/external/pure'
Synchronizing submodule url for 'modules/syntax-highlighting/external'
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:16> git submodule update --init --recursive
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:19> ln -sf /Users/shun.tagami/dotfiles/.dein.toml /Users/shun.tagami/.dein.toml
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:20> ln -sf /Users/shun.tagami/dotfiles/.editorconfig /Users/shun.tagami/.editorconfig
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:21> ln -sf /Users/shun.tagami/dotfiles/.gemrc /Users/shun.tagami/.gemrc
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:22> ln -sf /Users/shun.tagami/dotfiles/.gitconfig /Users/shun.tagami/.gitconfig
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:23> ln -sf /Users/shun.tagami/dotfiles/.gitignore_global /Users/shun.tagami/.gitignore_global
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:24> ln -sf /Users/shun.tagami/dotfiles/.golangci.yml /Users/shun.tagami/.golangci.yml
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:25> ln -sf /Users/shun.tagami/dotfiles/.my.cnf /Users/shun.tagami/.my.cnf
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:26> ln -sf /Users/shun.tagami/dotfiles/.npmrc /Users/shun.tagami/.npmrc
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:27> ln -sf /Users/shun.tagami/dotfiles/.ocamlinit /Users/shun.tagami/.ocamlinit
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:28> ln -sf /Users/shun.tagami/dotfiles/.vimrc /Users/shun.tagami/.vimrc
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:29> ln -sf /Users/shun.tagami/dotfiles/.zpreztorc /Users/shun.tagami/.zpreztorc
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:30> ln -sf /Users/shun.tagami/dotfiles/.zshenv /Users/shun.tagami/.zshenv
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:31> ln -sf /Users/shun.tagami/dotfiles/.zshrc /Users/shun.tagami/.zshrc
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:33> [[ darwin22.0 == darwin* ]]
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:34> grep -sq 'require('\''keyboard'\'')' /Users/shun.tagami/.hammerspoon/init.lua
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:35> ln -sf /Users/shun.tagami/dotfiles/hammerspoon/init.lua /Users/shun.tagami/.hammerspoon/init.lua
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:36> ln -sf /Users/shun.tagami/dotfiles/hammerspoon /Users/shun.tagami/.hammerspoon/keyboard
+/Users/shun.tagami/dotfiles/scripts/deploy.sh:41> ln -s /Users/shun.tagami/dotfiles/karabiner /Users/shun.tagami/.config
ln: /Users/shun.tagami/.config/karabiner: File exists
```
