### ISSUE TITLE
display_manager

### ISSUE THREAD

**Issue by shuntagami** [shuntagami/dotfiles#30]
```
~/dotfiles/scripts main*
❯ ./display_manager.py -h
Traceback (most recent call last):
  File "/Users/shun.tagami/dotfiles/scripts/./display_manager.py", line 27, in <module>
    from display_manager_lib import *   # The Display Manager Library
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shun.tagami/dotfiles/scripts/display_manager_lib.py", line 27, in <module>
    import objc             # access Objective-C functions and variables
    ^^^^^^^^^^^
ModuleNotFoundError: No module named 'objc'
```

**Comment by shuntagami** [comment]
`pip3 install pyobjc` resolved this

**Comment by shuntagami** [comment]
need `pip3 install pyobjc --break-system-packages`
